# Build go_torrent library for iOS
workflows:
    go_torrent:
      name: go_torrent
      instance_type: mac_mini_m1
      max_build_duration: 60
      # working_directory: go_torrent
      environment:
        groups:
          - ios
        vars:
          PUBLIC_ENV_VAR: "CGO_ENABLED=1 GOOS=ios GOARCH=arm64 SDK=iphoneos SDK_PATH=`xcrun --sdk $SDK --show-sdk-path` CLANG=`xcrun --sdk $SDK --find clang` CARCH='arm64' CGO_CFLAGS='-fembed-bitcode'"
        xcode: latest
        # cocoapods: default
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: '*'
            include: true
            source: true
        cancel_previous_builds: true
      scripts:
        
          - |
            #!/bin/bash
            set -e
            set -x
            if [ ! -f /usr/local/go/bin/go ]; then
              if [ ! -f go1.20.6.darwin-arm64.pkg ]; then
                wget https://go.dev/dl/go1.20.6.darwin-arm64.pkg
              fi
              sudo installer -pkg go1.20.6.darwin-arm64.pkg -target /
            fi
          - |
            #!/bin/bash
            set -e
            set -x
            echo "Building go_torrent for iOS"
            mkdir -p build/ios
            go mod init yusing/go_torrent/v2
            go mod tidy
            go build -tags ios -o ../build/ios/libtorrent_go_ios.a -buildmode=c-archive
            cd ..
            echo "Building go_torrent for iOS completed"
      artifacts:
          - build/ios/*.a