# Build go_torrent library for iOS
workflows:
    go_torrent:
      name: go_torrent
      instance_type: mac_mini_m1
      max_build_duration: 60
      environment:
        groups:
          - ios
        xcode: latest
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: '*'
            include: true
            source: true
        cancel_previous_builds: true
      scripts:
        
          - |
            #!/bin/bash
            set -e
            set -x
            if [ ! -f /usr/local/go/bin/go ]; then
              if [ ! -f go1.20.6.darwin-arm64.pkg ]; then
                wget https://go.dev/dl/go1.20.6.darwin-arm64.pkg
              fi
              sudo installer -pkg go1.20.6.darwin-arm64.pkg -target /
            fi
          - |
            #!/bin/bash
            set -e
            set -x
            cat clangwrap.sh
            chmod +x clangwrap.sh
            echo "Building go_torrent for iOS"
            mkdir -p build/ios
            go mod init yusing/go_torrent/v2
            go mod tidy
            SDK=iphoneos
            SDK_PATH=`xcrun --sdk $SDK --show-sdk-path` \
            CLANG=`xcrun --sdk $SDK --find clang` \
            CC=$(PWD)/clangwrap.sh \
            CXX=$(PWD)/clangwrap.sh \
            CARCH='arm64' \
            CGO_CFLAGS='-fembed-bitcode' \
            CGO_ENABLED=1 \
            GOOS=ios \
            GOARCH=arm64 \
            go build -tags ios -o build/ios/libtorrent_go_ios.a -buildmode=c-archive -ldflags="-s -w"
            echo "Building go_torrent for iOS completed"
            file build/ios/libtorrent_go_ios.a
      publishing:
        scripts:
            - name: report build status
              script: |
                if [ -a build/ios/libtorrent_go_ios.a ]; then
                  echo "Build succeeded"
                  exit 0
                else
                  echo "Build failed, no libtorrent_go_ios.a found"
                  ls -l build/ios
                  echo "Current directory: $PWD"
                  ls -l
                  exit 1
                fi
      artifacts:
          - build/ios/libtorrent_go_ios.a