# Build go_torrent library for iOS
workflows:
    go_torrent:
      name: go_torrent
      instance_type: mac_mini_m1
      max_build_duration: 60
      environment:
        groups:
          - ios
        xcode: latest
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: '*'
            include: true
            source: true
        cancel_previous_builds: true
      scripts:
        
          - |
            #!/bin/bash
            set -e
            set -x
            if [ ! -f /usr/local/go/bin/go ]; then
              if [ ! -f go1.21.0.darwin-arm64.pkg ]; then
                wget https://go.dev/dl/go1.21.0.darwin-arm64.pkg
              fi
              sudo installer -pkg go1.21.0.darwin-arm64.pkg -target /
            fi
          - |
            #!/bin/bash
            set -e
            set -x
            chmod +x build_ios.sh && ./build_ios.sh
      publishing:
        scripts:
            - name: report build status
              script: |
                if [ -a build/ios/libtorrent_go_ios.a ]; then
                  echo "Build succeeded"
                  exit 0
                else
                  echo "Build failed, no libtorrent_go_ios.a found"
                  ls -l build/ios
                  echo "Current directory: $PWD"
                  ls -l
                  exit 1
                fi
      artifacts:
          - build/ios/libtorrent_go_ios.a